"""empty message

Revision ID: 39866a6fbdbe
Revises: 76a0e0a8bc7c
Create Date: 2023-01-25 14:47:07.265844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39866a6fbdbe'
down_revision = '76a0e0a8bc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('senha')

    # ### end Alembic commands ###
