"""empty message

Revision ID: 76a0e0a8bc7c
Revises: 237e59b7d73c
Create Date: 2023-01-25 10:55:56.602008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a0e0a8bc7c'
down_revision = '237e59b7d73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remedio', sa.String(length=30), nullable=True),
    sa.Column('id_remedio', sa.Integer(), nullable=True),
    sa.Column('qnt_estoque', sa.Integer(), nullable=True),
    sa.Column('qnt_ideal', sa.Integer(), nullable=True),
    sa.Column('comprar', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_remedio'], ['medicine.id'], ),
    sa.ForeignKeyConstraint(['remedio'], ['medicine.nome'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist')
    # ### end Alembic commands ###
